function beam = beamInit(x, y, z, thtx, thty, Pz, gamma, charge)
    beam = struct( ...
        'x', x, ...
        'y', y, ...
        'z', z, ...
        'thtx', thtx, ...
        'thty', thty, ...
        'Pz', Pz, ...
        'gamma', gamma, ...
        'charge', charge ...
      );
end